/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as FamilyRecipeGyozaRouteImport } from './routes/family-recipe.gyoza'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRecipeGyozaRoute = FamilyRecipeGyozaRouteImport.update({
  id: '/family-recipe/gyoza',
  path: '/family-recipe/gyoza',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes': typeof RecipesRoute
  '/family-recipe/gyoza': typeof FamilyRecipeGyozaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes': typeof RecipesRoute
  '/family-recipe/gyoza': typeof FamilyRecipeGyozaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipes': typeof RecipesRoute
  '/family-recipe/gyoza': typeof FamilyRecipeGyozaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recipes' | '/family-recipe/gyoza'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipes' | '/family-recipe/gyoza'
  id: '__root__' | '/' | '/recipes' | '/family-recipe/gyoza'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesRoute: typeof RecipesRoute
  FamilyRecipeGyozaRoute: typeof FamilyRecipeGyozaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-recipe/gyoza': {
      id: '/family-recipe/gyoza'
      path: '/family-recipe/gyoza'
      fullPath: '/family-recipe/gyoza'
      preLoaderRoute: typeof FamilyRecipeGyozaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesRoute: RecipesRoute,
  FamilyRecipeGyozaRoute: FamilyRecipeGyozaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
